name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Specify your Node.js version

    - name: Install Dependencies
      run: npm install  # Install project dependencies

    - name: Build
      run: npm run build  # Build your Vite project, outputting files to 'dist'

    - name: Call Hostinger Webhook
      run: |
        curl -X POST -H "Content-Type: application/json" \