name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Specify your Node.js version

    - name: Install Dependencies
      run: npm install  # Install project dependencies

    - name: Build
      run: npm run build  # Build your Vite project, outputting files to 'dist'

    - name: Push generated webpage to another repository
      uses: nkoppel/push-files-to-another-repository@1.1.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-files: 'dist/'
        destination-username: 'c0d3cisco'
        destination-repository: 'porfolio_production'
        destination-branch: 'main'
        commit-email: 'c0d3cisco@yahoo.com'
        commit-username: 'c0d3cisco'
        commit-message: 'Deploy to Hostinger'