name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Specify your Node.js version

    - name: Install Dependencies
      run: npm install  # Install project dependencies

    - name: Build
      run: npm run build  # Build your Vite project, outputting files to 'dist'
      env:
        VITE_APP_EMAILJS_SERVICE_ID: ${{ secrets.VITE_APP_EMAILJS_SERVICE_ID }}
        VITE_APP_EMAILJS_TEMPLATE_ID: ${{ secrets.VITE_APP_EMAILJS_TEMPLATE_ID }}
        VITE_APP_EMAILJS_PUBLIC_KEY: ${{ secrets.VITE_APP_EMAILJS_PUBLIC_KEY }}



    - name: Push generated webpage to another repository
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      run: |
        git config --global user.name c0d3cisco
        git config --global user.email 'c0d3cisco@yahoo.com'
        git clone https://github.com/c0d3cisco/porfolio_production.git
        cp -r dist/* porfolio_production/
        cd porfolio_production
        git add .
        git commit -m 'Update from build'
        git push https://${API_TOKEN_GITHUB}@github.com/c0d3cisco/porfolio_production.git