name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Specify your Node.js version

    - name: Install Dependencies
      run: npm install  # Install project dependencies

    - name: Build
      run: npm run build  # Build your Vite project, outputting files to 'dist'

    - name: Push generated webpage to another repository
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      run: |
        #!/bin/sh -l

        set -e  # if a command fails exit the script
        set -u  # script fails if trying to access an undefined variable

        echo
        echo "##### Starting #####"
        SOURCE_FILES=dist/*
        DESTINATION_USERNAME=c0d3cisco
        DESTINATION_REPOSITORY=porfolio_production
        DESTINATION_BRANCH=main
        DESTINATION_DIRECTORY= .
        COMMIT_USERNAME=c0d3cisco
        COMMIT_EMAIL=c0d3cisco@yahoo.com
        COMMIT_MESSAGE=test

        if [ -z "$COMMIT_USERNAME" ]
        then
          COMMIT_USERNAME="$DESTINATION_USERNAME"
        fi

        CLONE_DIRECTORY=$(mktemp -d)

        echo
        echo "##### Cloning source git repository #####"
        # Setup git
        git config --global user.email "$COMMIT_EMAIL"
        git config --global user.name "$COMMIT_USERNAME"

        # Remove git directory if it exists to prevent errors
        rm -rf .git

        git clone "https://github.com/$GITHUB_REPOSITORY.git" repo

        cd repo
        ls -la

        echo
        echo "##### Cloning destination git repository #####"

        git clone --single-branch --branch "$DESTINATION_BRANCH" "https://$API_TOKEN_GITHUB@github.com/$DESTINATION_USERNAME/        $DESTINATION_REPOSITORY.git" "$CLONE_DIRECTORY"
        ls -la "$CLONE_DIRECTORY"

        echo
        echo "##### Copying contents to git repo #####"
        mkdir -p "$CLONE_DIRECTORY/$DESTINATION_DIRECTORY"
        cp -rvf $SOURCE_FILES "$CLONE_DIRECTORY/$DESTINATION_DIRECTORY"
        cd "$CLONE_DIRECTORY"

        echo
        echo "##### Adding git commit #####"

        ORIGIN_COMMIT="https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA"
        COMMIT_MESSAGE="${COMMIT_MESSAGE/ORIGIN_COMMIT/$ORIGIN_COMMIT}"

        git add .
        git status

        # don't commit if no changes were made
        git diff-index --quiet HEAD || git commit --message "$COMMIT_MESSAGE"

        echo
        echo "##### Pushing git commit #####"
        # --set-upstream: sets the branch when pushing to a branch that does not exist
        git push origin --set-upstream "$DESTINATION_BRANCH"